"""empty message

Revision ID: e2cf5a5398c2
Revises: 1b7e03aadebc
Create Date: 2019-12-24 18:27:37.054967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2cf5a5398c2'
down_revision = '1b7e03aadebc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drawings', sa.Column('s3_filename', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drawings', 's3_filename')
    # ### end Alembic commands ###
