"""empty message

Revision ID: ef81b4fce3ac
Revises: e2cf5a5398c2
Create Date: 2020-01-18 18:15:28.721982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef81b4fce3ac'
down_revision = 'e2cf5a5398c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drawings', sa.Column('actual_label', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drawings', 'actual_label')
    # ### end Alembic commands ###
